### ISSUE TITLE
影视仓投屏里就找不到设备：DLNAmpvRenderer

### ISSUE THREAD

**Issue by hgc357341051** [PCigales/DLNAmpvRenderer#3]
影视仓：https://drive.uc.cn/s/b437317346a14
不知道为什么，抖音，bilibili都很正常

**Comment by PCigales** [comment]
I am sorry, but I don't speak Chinese. I used Google Translate to try to understand your post, and it seems that you report that an Android app named "Movie and TV Warehouse" cannot find the mpv dlna renderer. I downloaded and installed this app, but it is totally in Chinese, so I have no idea of how to display available upnp renderers, although I attempted to click everywhere.

I am afraid I cannot bring any help to you if you don't provide me with explanations either in English or in French.
